/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.node;

import Lexico.analysis.*;

public final class TAtrib extends Token
{
    public TAtrib()
    {
        super.setText("=");
    }

    public TAtrib(int line, int pos)
    {
        super.setText("=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TAtrib(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtrib(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TAtrib text.");
    }
}
