/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.node;

import Lexico.analysis.*;

public final class TBlank extends Token
{
    public TBlank()
    {
        super.setText(" ");
    }

    public TBlank(int line, int pos)
    {
        super.setText(" ");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TBlank(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBlank(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TBlank text.");
    }
}
