/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.node;

import Lexico.analysis.*;

public final class TComman extends Token
{
    public TComman()
    {
        super.setText(",");
    }

    public TComman(int line, int pos)
    {
        super.setText(",");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TComman(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComman(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TComman text.");
    }
}
