/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.node;

import Lexico.analysis.*;

public final class TForeach extends Token
{
    public TForeach()
    {
        super.setText("for each");
    }

    public TForeach(int line, int pos)
    {
        super.setText("for each");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TForeach(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTForeach(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TForeach text.");
    }
}
