/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.node;

import Lexico.analysis.*;

public final class TLequal extends Token
{
    public TLequal()
    {
        super.setText("<=");
    }

    public TLequal(int line, int pos)
    {
        super.setText("<=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLequal(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLequal(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLequal text.");
    }
}
