/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.node;

import Lexico.analysis.*;

public final class TLsbrack extends Token
{
    public TLsbrack()
    {
        super.setText("[");
    }

    public TLsbrack(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLsbrack(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLsbrack(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLsbrack text.");
    }
}
