/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.node;

import Lexico.analysis.*;

public final class TNint extends Token
{
    public TNint()
    {
        super.setText("numint");
    }

    public TNint(int line, int pos)
    {
        super.setText("numint");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNint(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNint(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNint text.");
    }
}
