/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.node;

import Lexico.analysis.*;

public final class TNreal extends Token
{
    public TNreal()
    {
        super.setText("numfloat");
    }

    public TNreal(int line, int pos)
    {
        super.setText("numfloat");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNreal(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNreal(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNreal text.");
    }
}
