/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.node;

import Lexico.analysis.*;

public final class TRcbrack extends Token
{
    public TRcbrack()
    {
        super.setText("}");
    }

    public TRcbrack(int line, int pos)
    {
        super.setText("}");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRcbrack(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRcbrack(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRcbrack text.");
    }
}
