/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.node;

import Lexico.analysis.*;

public final class TRsbrack extends Token
{
    public TRsbrack()
    {
        super.setText("]");
    }

    public TRsbrack(int line, int pos)
    {
        super.setText("]");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRsbrack(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRsbrack(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRsbrack text.");
    }
}
