/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.lexer;

import java.io.*;
import java.util.*;
import Lexico.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;

        if(gotoTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Lexer.class.getResourceAsStream("lexer.dat")));

                // read gotoTable
                int length = s.readInt();
                gotoTable = new int[length][][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][][];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        length = s.readInt();
                        gotoTable[i][j] = new int[length][3];
                        for(int k = 0; k < gotoTable[i][j].length; k++)
                        {
                            for(int l = 0; l < 3; l++)
                            {
                                gotoTable[i][j][k][l] = s.readInt();
                            }
                        }
                    }
                }

                // read accept
                length = s.readInt();
                accept = new int[length][];
                for(int i = 0; i < accept.length; i++)
                {
                    length = s.readInt();
                    accept[i] = new int[length];
                    for(int j = 0; j < accept[i].length; j++)
                    {
                        accept[i][j] = s.readInt();
                    }
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
            }
        }
    }

    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(int line, int pos) { return new TScolon(line, pos); }
    Token new1(int line, int pos) { return new TComman(line, pos); }
    Token new2(int line, int pos) { return new TLsbrack(line, pos); }
    Token new3(int line, int pos) { return new TRsbrack(line, pos); }
    Token new4(int line, int pos) { return new TInt(line, pos); }
    Token new5(int line, int pos) { return new TChar(line, pos); }
    Token new6(int line, int pos) { return new TFloat(line, pos); }
    Token new7(int line, int pos) { return new TLpar(line, pos); }
    Token new8(int line, int pos) { return new TRpar(line, pos); }
    Token new9(int line, int pos) { return new TVoid(line, pos); }
    Token new10(int line, int pos) { return new TLcbrack(line, pos); }
    Token new11(int line, int pos) { return new TRcbrack(line, pos); }
    Token new12(int line, int pos) { return new TAtrib(line, pos); }
    Token new13(int line, int pos) { return new TIf(line, pos); }
    Token new14(int line, int pos) { return new TWhile(line, pos); }
    Token new15(int line, int pos) { return new TFor(line, pos); }
    Token new16(int line, int pos) { return new TForeach(line, pos); }
    Token new17(int line, int pos) { return new TColon(line, pos); }
    Token new18(int line, int pos) { return new TReturn(line, pos); }
    Token new19(int line, int pos) { return new TElse(line, pos); }
    Token new20(int line, int pos) { return new TNint(line, pos); }
    Token new21(int line, int pos) { return new TNreal(line, pos); }
    Token new22(int line, int pos) { return new TString(line, pos); }
    Token new23(int line, int pos) { return new TLchar(line, pos); }
    Token new24(int line, int pos) { return new TNew(line, pos); }
    Token new25(int line, int pos) { return new TMinus(line, pos); }
    Token new26(int line, int pos) { return new TPlus(line, pos); }
    Token new27(int line, int pos) { return new TTimes(line, pos); }
    Token new28(int line, int pos) { return new TDiv(line, pos); }
    Token new29(int line, int pos) { return new TEqual(line, pos); }
    Token new30(int line, int pos) { return new TLequal(line, pos); }
    Token new31(int line, int pos) { return new TGequal(line, pos); }
    Token new32(int line, int pos) { return new TLess(line, pos); }
    Token new33(int line, int pos) { return new TGreater(line, pos); }
    Token new34(int line, int pos) { return new TNot(line, pos); }
    Token new35(int line, int pos) { return new TAnd(line, pos); }
    Token new36(int line, int pos) { return new TOr(line, pos); }
    Token new37(String text, int line, int pos) { return new TSpace(text, line, pos); }
    Token new38(String text, int line, int pos) { return new TId(text, line, pos); }
    Token new39(String text, int line, int pos) { return new TNumero(text, line, pos); }
    Token new40(String text, int line, int pos) { return new TComment(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {38, 38, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {47, 47, 13}, {48, 57, 14}, {58, 58, 15}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {62, 62, 19}, {65, 90, 20}, {91, 91, 21}, {93, 93, 22}, {97, 98, 23}, {99, 99, 24}, {100, 100, 23}, {101, 101, 25}, {102, 102, 26}, {103, 104, 23}, {105, 105, 27}, {106, 109, 23}, {110, 110, 28}, {111, 113, 23}, {114, 114, 29}, {115, 115, 30}, {116, 117, 23}, {118, 118, 31}, {119, 119, 32}, {120, 122, 23}, {123, 123, 33}, {124, 124, 34}, {125, 125, 35}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 36}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {{38, 38, 37}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{42, 42, 38}, {47, 47, 39}, },
            {{48, 57, 40}, },
            {},
            {},
            {{61, 61, 41}, },
            {{61, 61, 42}, },
            {{61, 61, 43}, },
            {{48, 57, 44}, {65, 90, 45}, {97, 122, 46}, },
            {},
            {},
            {{48, 122, -22}, },
            {{48, 90, -22}, {97, 103, 46}, {104, 104, 47}, {105, 122, 46}, },
            {{48, 90, -22}, {97, 107, 46}, {108, 108, 48}, {109, 122, 46}, },
            {{48, 107, -27}, {108, 108, 49}, {109, 110, 46}, {111, 111, 50}, {112, 122, 46}, },
            {{48, 90, -22}, {97, 101, 46}, {102, 102, 51}, {103, 109, 46}, {110, 110, 52}, {111, 122, 46}, },
            {{48, 90, -22}, {97, 100, 46}, {101, 101, 53}, {102, 116, 46}, {117, 117, 54}, {118, 122, 46}, },
            {{48, 100, -30}, {101, 101, 55}, {102, 122, 46}, },
            {{48, 90, -22}, {97, 115, 46}, {116, 116, 56}, {117, 122, 46}, },
            {{48, 90, -22}, {97, 110, 46}, {111, 111, 57}, {112, 122, 46}, },
            {{48, 103, -26}, {104, 104, 58}, {105, 122, 46}, },
            {},
            {{124, 124, 59}, },
            {},
            {{9, 32, -2}, },
            {},
            {{0, 41, 60}, {42, 42, 61}, {43, 127, 60}, },
            {{0, 9, 62}, {10, 10, 63}, {11, 12, 62}, {13, 13, 64}, {14, 127, 62}, },
            {{48, 57, 40}, },
            {},
            {},
            {},
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 90, -22}, {97, 97, 65}, {98, 122, 46}, },
            {{48, 90, -22}, {97, 114, 46}, {115, 115, 66}, {116, 122, 46}, },
            {{48, 110, -33}, {111, 111, 67}, {112, 122, 46}, },
            {{48, 90, -22}, {97, 113, 46}, {114, 114, 68}, {115, 122, 46}, },
            {{48, 122, -22}, },
            {{48, 115, -32}, {116, 116, 69}, {117, 122, 46}, },
            {{48, 90, -22}, {97, 118, 46}, {119, 119, 70}, {120, 122, 46}, },
            {{48, 90, -22}, {97, 108, 46}, {109, 109, 71}, {110, 122, 46}, },
            {{48, 115, -32}, {116, 116, 72}, {117, 122, 46}, },
            {{48, 113, -52}, {114, 114, 73}, {115, 122, 46}, },
            {{48, 90, -22}, {97, 104, 46}, {105, 105, 74}, {106, 122, 46}, },
            {{48, 104, -59}, {105, 105, 75}, {106, 122, 46}, },
            {},
            {{0, 127, -40}, },
            {{0, 41, 76}, {42, 42, 61}, {43, 46, 76}, {47, 47, 77}, {48, 127, 76}, },
            {{0, 127, -41}, },
            {},
            {{10, 10, 78}, },
            {{48, 113, -52}, {114, 114, 79}, {115, 122, 46}, },
            {{48, 100, -30}, {101, 101, 80}, {102, 122, 46}, },
            {{48, 90, -22}, {97, 97, 81}, {98, 122, 46}, },
            {{32, 32, 82}, {48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 101, -29}, {102, 102, 83}, {103, 104, 46}, {105, 105, 84}, {106, 122, 46}, },
            {{48, 90, -22}, {97, 116, 46}, {117, 117, 85}, {118, 122, 46}, },
            {{48, 104, -59}, {105, 105, 86}, {106, 122, 46}, },
            {{48, 90, -22}, {97, 99, 46}, {100, 100, 87}, {101, 122, 46}, },
            {{48, 107, -27}, {108, 108, 88}, {109, 122, 46}, },
            {{0, 41, 89}, {42, 42, 90}, {43, 127, 89}, },
            {},
            {},
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 115, -32}, {116, 116, 91}, {117, 122, 46}, },
            {{101, 101, 92}, },
            {{48, 107, -27}, {108, 108, 93}, {109, 122, 46}, },
            {{48, 90, -22}, {97, 109, 46}, {110, 110, 94}, {111, 122, 46}, },
            {{48, 113, -52}, {114, 114, 95}, {115, 122, 46}, },
            {{48, 109, -86}, {110, 110, 96}, {111, 122, 46}, },
            {{48, 122, -22}, },
            {{48, 100, -30}, {101, 101, 97}, {102, 122, 46}, },
            {{0, 127, -78}, },
            {{0, 41, 76}, {42, 42, 90}, {43, 127, -63}, },
            {{48, 122, -22}, },
            {{97, 97, 98}, },
            {{48, 110, -33}, {111, 111, 99}, {112, 122, 46}, },
            {{48, 115, -32}, {116, 116, 100}, {117, 122, 46}, },
            {{48, 109, -86}, {110, 110, 101}, {111, 122, 46}, },
            {{48, 90, -22}, {97, 102, 46}, {103, 103, 102}, {104, 122, 46}, },
            {{48, 122, -22}, },
            {{99, 99, 103}, },
            {{48, 90, -22}, {97, 97, 104}, {98, 122, 46}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{104, 104, 105}, },
            {{48, 115, -32}, {116, 116, 106}, {117, 122, 46}, },
            {},
            {{48, 122, -22}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 37, 37, 37, 37, 34, -1, 7, 8, 27, 26, 1, 25, 28, 39, 17, 0, 32, 12, 33, 38, 2, 3, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 10, -1, 11, 37, 35, -1, -1, 39, 30, 29, 31, 38, 38, 38, 38, 38, 38, 38, 13, 38, 38, 38, 38, 38, 38, 38, 36, -1, -1, -1, 40, 40, 38, 38, 38, 15, 4, 24, 38, 38, 38, 38, 38, -1, 40, 40, 5, 19, 38, -1, 38, 38, 38, 38, 9, 38, -1, -1, 6, -1, 38, 38, 38, 38, 14, -1, 38, 20, 18, 22, -1, 38, 16, 21, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }
}
