/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.analysis;

import Lexico.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseTScolon(TScolon node);
    void caseTComman(TComman node);
    void caseTLsbrack(TLsbrack node);
    void caseTRsbrack(TRsbrack node);
    void caseTInt(TInt node);
    void caseTChar(TChar node);
    void caseTFloat(TFloat node);
    void caseTLpar(TLpar node);
    void caseTRpar(TRpar node);
    void caseTVoid(TVoid node);
    void caseTLcbrack(TLcbrack node);
    void caseTRcbrack(TRcbrack node);
    void caseTAtrib(TAtrib node);
    void caseTIf(TIf node);
    void caseTWhile(TWhile node);
    void caseTFor(TFor node);
    void caseTForeach(TForeach node);
    void caseTColon(TColon node);
    void caseTReturn(TReturn node);
    void caseTElse(TElse node);
    void caseTNint(TNint node);
    void caseTNreal(TNreal node);
    void caseTString(TString node);
    void caseTLchar(TLchar node);
    void caseTNew(TNew node);
    void caseTMinus(TMinus node);
    void caseTPlus(TPlus node);
    void caseTTimes(TTimes node);
    void caseTDiv(TDiv node);
    void caseTEqual(TEqual node);
    void caseTLequal(TLequal node);
    void caseTGequal(TGequal node);
    void caseTLess(TLess node);
    void caseTGreater(TGreater node);
    void caseTNot(TNot node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTSpace(TSpace node);
    void caseTId(TId node);
    void caseTNumero(TNumero node);
    void caseTComment(TComment node);
    void caseEOF(EOF node);
}
