/* This file was generated by SableCC (http://www.sablecc.org/). */

package Lexico.analysis;

import java.util.*;
import Lexico.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(Node node)
    {
    }

    public void defaultOut(Node node)
    {
    }

    public void caseStart(Start node)
    {
        inStart(node);
        node.getPProgram().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        if(node.getPalavra() != null)
        {
            node.getPalavra().apply(this);
        }
        if(node.getScolon() != null)
        {
            node.getScolon().apply(this);
        }
        outAProgram(node);
    }
}
